global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir_danilyuk_msg'
