version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_IMAGE_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_APP_IMAGE_VER}
    ports:
      - ${PORT_PUMA}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_APP_IMAGE_VER}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_APP_IMAGE_VER}
    networks:
      - front_net
      - back_net
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
